package de.slisson.mps.mbeddr1687.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import java.util.Map;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.runtime.PropertyConstraintsDescriptor;
import java.util.HashMap;
import jetbrains.mps.smodel.runtime.base.BasePropertyConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class NumberLiteral_Constraints extends BaseConstraintsDescriptor {
  public NumberLiteral_Constraints() {
    super(MetaAdapterFactory.getConcept(0x356351fdbd414ac3L, 0x90a63afbbb7a6831L, 0x246dff530ab3a413L, "de.slisson.mps.mbeddr1687.structure.NumberLiteral"));
  }

  @Override
  protected Map<SProperty, PropertyConstraintsDescriptor> getSpecifiedProperties() {
    Map<SProperty, PropertyConstraintsDescriptor> properties = new HashMap<SProperty, PropertyConstraintsDescriptor>();
    properties.put(MetaAdapterFactory.getProperty(0x356351fdbd414ac3L, 0x90a63afbbb7a6831L, 0x246dff530ab3a413L, 0x246dff530ab3a414L, "value"), new BasePropertyConstraintsDescriptor(MetaIdFactory.propId(0x356351fdbd414ac3L, 0x90a63afbbb7a6831L, 0x246dff530ab3a413L, 0x246dff530ab3a414L), this) {
      @Override
      public boolean hasOwnValidator() {
        return true;
      }
      @Override
      public boolean validateValue(SNode node, String propertyValue) {
        String propertyName = "value";
        if (isEmptyString((SPropertyOperations.getString(propertyValue)))) {
          return false;
        }
        return (SPropertyOperations.getString(propertyValue)).matches("[0-9]+");
      }
    });
    return properties;
  }
  private static boolean isEmptyString(String str) {
    return str == null || str.length() == 0;
  }
}
