package de.slisson.mps.mbeddr1687.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private final ConceptPresentation props_Expression = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_ExpressionStatement = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Method = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_NumberLiteral = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Statement = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_StatementList = new ConceptPresentationBuilder().create();

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.Expression:
        return props_Expression;
      case LanguageConceptSwitch.ExpressionStatement:
        return props_ExpressionStatement;
      case LanguageConceptSwitch.Method:
        return props_Method;
      case LanguageConceptSwitch.NumberLiteral:
        return props_NumberLiteral;
      case LanguageConceptSwitch.Statement:
        return props_Statement;
      case LanguageConceptSwitch.StatementList:
        return props_StatementList;
    }
    return null;
  }
}
