package de.slisson.mps.mbeddr1687.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Expression = 0;
  public static final int ExpressionStatement = 1;
  public static final int Method = 2;
  public static final int NumberLiteral = 3;
  public static final int Statement = 4;
  public static final int StatementList = 5;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x356351fdbd414ac3L, 0x90a63afbbb7a6831L);
    builder.put(0x246dff530ab3a3baL, Expression);
    builder.put(0x246dff530ab3a3b9L, ExpressionStatement);
    builder.put(0x246dff530ab37ce8L, Method);
    builder.put(0x246dff530ab3a413L, NumberLiteral);
    builder.put(0x246dff530ab3a3c5L, Statement);
    builder.put(0x246dff530ab3a3b8L, StatementList);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
