package de.slisson.mps.mbeddr1687.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.menus.substitute.SubstituteMenuBase;
import org.jetbrains.annotations.NotNull;
import java.util.List;
import jetbrains.mps.lang.editor.menus.MenuPart;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuItem;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuContext;
import java.util.ArrayList;
import com.mbeddr.mpsutil.grammarcells.runtime.menu.GrammarCellsSubstituteMenuPart;
import org.jetbrains.mps.openapi.module.SModule;
import org.jetbrains.mps.openapi.module.SRepository;
import org.jetbrains.mps.openapi.persistence.PersistenceFacade;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class GrammarCellsSubstituteMenu_StatementList extends SubstituteMenuBase {
  public GrammarCellsSubstituteMenu_StatementList() {
    super(true);
  }
  @NotNull
  @Override
  protected List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> getParts(final SubstituteMenuContext _context) {
    List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> result = new ArrayList<MenuPart<SubstituteMenuItem, SubstituteMenuContext>>();
    result.add(new GrammarCellsSubstituteMenu_StatementList.GrammarCellsSubstituteMenuPart_r6n9fs_a());
    return result;
  }
  private class GrammarCellsSubstituteMenuPart_r6n9fs_a extends GrammarCellsSubstituteMenuPart {
    @Override
    public SModule getModule(SRepository repository) {
      return PersistenceFacade.getInstance().createModuleReference("356351fd-bd41-4ac3-90a6-3afbbb7a6831(de.slisson.mps.mbeddr1687)").resolve(repository);
    }
    @Override
    public SAbstractConcept getExpectedOutputConcept() {
      return MetaAdapterFactory.getConcept(0x356351fdbd414ac3L, 0x90a63afbbb7a6831L, 0x246dff530ab3a3b8L, "de.slisson.mps.mbeddr1687.structure.StatementList");
    }
  }
}
